config/routes.rb
SampleApp::Application.routes.draw do
  resources :projects do
    resources :tasks do
      post :change_status
      post :calculate
    end
    resource :task do
      post :calculate
      post :sort
    end
  end
  resources :users do
    member do
      get :following, :followers
      # users_controllerにメソッドを書く
      post :upload_image
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tasks,    only: [:create, :destroy] do
    post :start
    post :finish
  end
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    if signed_in?
      @feed_items = @project.tasks.order(:order)
      @task = Task.new(project_id: @project.id)
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'プロジェクトを作成しました' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'プロジェクトを更新しました' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :start_date)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
    = f.label :start_date
    = f.date_field :start_date
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'タスク一覧', @project
\|
= link_to '戻る', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %thead
    %tr
      %th プロジェクト一覧
      %th
      %th
      %th

  %tbody
    - @projects.each do |project|
      %tr
        %td= project.name
        %td= link_to '開く', project
        %td= link_to '編集', edit_project_path(project)
        %td= link_to '削除', project, method: :delete, data: { confirm: '削除しますか' }

%br

= link_to '新規プロジェクトの作成', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b プロジェクト名:
  = @project.name

= link_to '編集', edit_project_path(@project)
= link_to '戻る', projects_path
= link_to '自動計算', calculate_project_task_path(@project), { method: "post", class: "btn btn-primary pull-right" }

= form_for @task, url: project_tasks_path(@project) do |f|
  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit '作成する', { class: "btn btn-large btn-primary" }

- if @feed_items.any?
  .table_container
    %table.table.table-striped.table-bordered{id: "task_table"}
      %thead
        %tr
          %th.content
            = "内容"
          %th
            = "担当者"
          %th.planed_time
            = "予定工数"
          %th.status
            = "ステータス"
          - (@project.start_date..(@project.start_date + 20)).each do |d|
            %th.day
              = d.strftime("%m/%d")
      %tbody.sortable
        - @feed_items.each do |feed_item|
          %tr{ data: {"task_id": feed_item.id}}
            %td
              = link_to feed_item.content, edit_project_task_path(@project, feed_item)
            %td
              = collection_select :task, :user, User.all, :id, :name, { selected: feed_item.user.id }, class: "select_user_field"
            %td
              %input.planed_time{value: feed_item.planed_time}
            %td
              = feed_item.status_for_display
              - if feed_item.not_started?
                = link_to "開始", task_start_path(task_id: feed_item.id, project_id: @project.id), method: :start, class: "btn btn-primary btn-sm"
              - if feed_item.working?
                = link_to "完了", task_finish_path(task_id: feed_item.id, project_id: @project.id), method: :finish, class: "btn btn-primary btn-sm"
              = link_to "削除", project_task_path(task_id: feed_item.id, project_id: @project.id), method: :delete, data: { confirm: "削除しますか？" }, title: feed_item.content, class: "btn btn-primary btn-sm"
            - (@project.start_date..(@project.start_date + 20)).each do |d|
              %td
                = feed_item.dailies.find_by(the_date: d).try(:planed_time)
                = feed_item.dailies.find_by(the_date: d).try(:actual_time)