config/routes.rb
SampleApp::Application.routes.draw do
  resources :projects do
    resources :tasks do
      post :change_status
      post :calculate
    end
    resource :task do
      post :calculate
      post :sort
    end
  end
  resources :users do
    member do
      get :following, :followers
      # users_controllerにメソッドを書く
      post :upload_image
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tasks,    only: [:create, :destroy] do
    post :start
    post :finish
  end
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/views/layouts/_footer.html.haml
%footer.footer
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Contact", contact_path
      %li
        %a{:href => "http://news.railstutorial.org/"} News

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .navbar-inner
      .container
        = link_to "sample app", root_path, id: "logo"
        %nav
          %ul.nav.pull-right
            %li= link_to "ホーム", root_path
            %li= link_to "ヘルプ", help_path
            - if signed_in?
              %li= link_to "ユーザー", users_path
              %li#fat-menu.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  アカウント
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Profile", current_user
                  %li= link_to "Settings", edit_user_path(current_user)
                  %li.divider
                  %li
                    = link_to "Sign out", signout_path, method: "delete"
            - else
              %li= link_to "Sign in", signin_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?